resources:
  - name: DevopsPractice
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: RealNewave/DevopsPractice

pipelines:
  - name: MyFirstPipeline
    steps:
    - name: build
      type: MvnBuild
      configuration:
        sourceLocation: .
        mvnCommand: clean install -ntp
        configFileLocation: .
        configFileName: mvn-art-config
        inputResources:
          - name: DevopsPractice
        integrations:
          - name: DevopsRepository
        runtime:
          type: image
          image:
            auto:
              language: java
              versions:
                - "11"
      execution:
        onStart:
          - javac -version
          - mvn --version